version: '3'

services:
  app:
    build: .
    ports:
      - "8080:8080"
      - "9229:9229"
    env_file: .env
    volumes:
      - .:/usr/app/

  postgre:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "cfgcmapy"
    